# Travis Continuous Integration Configuration File, based on ..
#   Generic MoveIt Travis Continuous Integration Configuration File
#   Works with all MoveIt! repositories/branches
#   Author: Dave Coleman, Jonathan Bohren
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=true    CATKIN_PARALLEL_JOBS='-p2'
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=false   NOT_TEST_INSTALL=true CATKIN_PARALLEL_JOBS='-p2'
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=true    NOT_TEST_INSTALL=true CATKIN_PARALLEL_JOBS='-p2' INSTALL_SRC="http://github.com/start-jsk/rtmros_tutorials" TEST_PKGS="hrpsys_ros_bridge_tutorials"
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=source  NOT_TEST_INSTALL=true CATKIN_PARALLEL_JOBS='-p2'
  - ROS_DISTRO=indigo ROSWS=wstool BUILDER=catkin    USE_DEB=true
  - TEST_TYPE=work_with_downstream  TEST_PACKAGE=hironx-ros-bridge ROS_DISTRO=hydro EXTRA_DEB="ros-hydro-roslint ros-hydro-robot-pose-ekf"
  - TEST_TYPE=work_with_315_1_10    TEST_PACKAGE=hironx-ros-bridge ROS_DISTRO=hydro EXTRA_DEB=ros-hydro-roslint
matrix:
  allow_failures:
  - env: ROS_DISTRO=indigo ROSWS=wstool BUILDER=catkin    USE_DEB=true
notifications:
  email:
    recipients:
      - k-okada@jsk.t.u-tokyo.ac.jp
      - iisaito@opensource-robotics.tokyo.jp
    on_success: always #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
before_script:
  - set -x
  - export REPOSITORY_NAME=`basename $PWD`
  - if [ "${INSTALL_SRC}" != "" ] ;then mkdir -p ~/ros/ws_$REPOSITORY_NAME/src; for src in $INSTALL_SRC; do git clone $src ~/ros/ws_$REPOSITORY_NAME/src/`basename ${src}`; done; fi;
script:
  - export ROS_PARALLEL_JOBS="-j2 -l2"
  - if [ "${TEST_TYPE}" == "" ] ; then source .travis/travis.sh; else source ./.travis_test.sh ; fi
